services:
  postgres:
    container_name: ${CLABS_INFINITEPIECES_PROJECT_NAME}-postgres
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: infinitepieces
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${CLABS_INFINITEPIECES_POSTGRES_SUPERUSER_PASSWORD:-postgres}
      CLABS_INFINITEPIECES_DB_PASSWORD: ${CLABS_INFINITEPIECES_DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
      - ./create_roles.sql:/opt/infinitepieces/create_roles.sql:ro

volumes:
  pgdata:
