server:
  port: 8080

spring:
  datasource:
    username: infinitepieces_app
    password: 'changeme'
  flyway:
    locations: classpath:db/migrations

infinitepieces:
  firebase:
    project-id: infinite-pieces
    google-certs-url: https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com
